name: uganda
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.2
  file_picker: ^10.0.0
  connectivity_plus: ^6.1.3
  path: ^1.8.3
  archive: ^3.4.10
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/texts/

