name: uganda
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.5
  file_picker: ^6.1.1
  path: ^1.8.3
  archive: ^3.4.10
  connectivity_plus: ^5.0.2
  window_manager: ^0.3.7
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/texts/

